### ISSUE TITLE
How can I update using this repo ?

### ISSUE THREAD

**Issue by norsasono** [MunGell/openshift-ghost-quickstart#1]
:cat:

**Comment by MunGell** [comment]
Hi @norsasono 

Could you please describe how you installed your blog initially - I will try to do the same and will let you know the best option there.

**Comment by norsasono** [comment]
Hi @MunGell 

I used openshift ghost quickstart from https://github.com/openshift-quickstart/openshift-ghost-quickstart/issues, which is actually still running ghost 0.7.5. I came here by your link on [this issue](https://github.com/openshift-quickstart/openshift-ghost-quickstart/issues/65)

I mean, do I (only) have to copy and merge the folder `node_module/ghost/`, `package.json`, and the default casper theme?

**Comment by MunGell** [comment]
@norsasono yes, these are the only files you need to copy to update your installation :)

**Comment by norsasono** [comment]
@MunGell Thank you so much :smile_cat:

**Comment by MunGell** [comment]
no worries!
