### ISSUE TITLE
How about 0.11.0 ?

### ISSUE THREAD

**Issue by 23W** [MunGell/openshift-ghost-quickstart#3]
Ghost was updated to 0.11.0 version. Can you update your depositary too? Ghost version 0.11.0 is not new featured version this is the important bug-fixing version (for example in 0.10.1 amp pages are damaged so 0.11.0 fixed it). 
Thank you.

**Comment by MunGell** [comment]
Hi @23W 

I'll update it as soon as I will have time - hopefully in the next several days or even today.

**Comment by MunGell** [comment]
It is done now

**Comment by 23W** [comment]
Greatest thank you!
