### ISSUE TITLE
Upgrade to 0.11.1

### ISSUE THREAD

**Issue by 23W** [MunGell/openshift-ghost-quickstart#4]
New ghost version 0.11.1 is released. May be, do you have to update your repository?

**Comment by 23W** [comment]
please, upgrade your repos. to 0.11.2 version.

**Comment by MunGell** [comment]
Hey @23W 

Yeah, I've seen the update notes. The repository will be updated shortly as soon as I will have time.
There is no need to open issue for every minor update the same day it was released :)

Meanwhile if you are really in a harry, I've set up this repository (and that was an initial intention) to be easily updated by anyone.

All I do for every update in this repository is running `make` command in the root on my CentOS machine.

I will close this ticket when this repo will be updated.
